const departure_data = {
  stops: [
    {
      stop_id: 4676,
      latitude: 44.948516,
      longitude: -93.329076,
      description: "Lake St W & France Ave S",
    },
    {
      stop_id: 42410,
      latitude: 44.947896,
      longitude: -93.329235,
      description: "Hwy 7 Svc Rd S & France Ave",
    },
    {
      stop_id: 46492,
      latitude: 44.948129,
      longitude: -93.328212,
      description: "Lake St Bus Loop & France",
    },
  ],
  alerts: [
    {
      stop_closed: false,
      alert_text:
        "The following stop is closed for Rts. 17 & 18 beginning at 5am until further notice: Nicollet Ave S & 18th St W - Stop #1200",
    },
    {
      stop_closed: false,
      alert_text:
        "Rt 17 detoured off Nicollet between Washington & 3rd/4th St & Marquette between Washington & 1st St from Feb 26 at 6am to Feb 27 at 6pm",
    },
    {
      stop_closed: false,
      alert_text:
        "Route 4 detoured off Hennepin between Washington and 1st St from Sat Feb 26 at 6:00 AM to Sun Feb 27 at 6:00 PM",
    },
  ],
  departures: [
    {
      actual: true,
      trip_id: "20560436-DEC21-MVS-BUS-Weekday-01",
      stop_id: 4676,
      departure_text: "7 Min",
      departure_time: 1645725181,
      description: "24St-Uptown / Tyler-Lake / St Louis Pk",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "D",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560467-DEC21-MVS-BUS-Weekday-01",
      stop_id: 46492,
      departure_text: "12:07",
      departure_time: 1645726020,
      description: "24St-Uptown / Lake-France",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "B",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560438-DEC21-MVS-BUS-Weekday-01",
      stop_id: 4676,
      departure_text: "12:23",
      departure_time: 1645726980,
      description: "24St-Uptown / Tyler-Lake / St Louis Pk",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "D",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560468-DEC21-MVS-BUS-Weekday-01",
      stop_id: 46492,
      departure_text: "12:39",
      departure_time: 1645727940,
      description: "24St-Uptown / Lake-France",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "B",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560437-DEC21-MVS-BUS-Weekday-01",
      stop_id: 4676,
      departure_text: "12:53",
      departure_time: 1645728780,
      description: "24St-Uptown / Tyler-Lake / St Louis Pk",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "D",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560469-DEC21-MVS-BUS-Weekday-01",
      stop_id: 46492,
      departure_text: "1:09",
      departure_time: 1645729740,
      description: "24St-Uptown / Lake-France",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "B",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "20560432-DEC21-MVS-BUS-Weekday-01",
      stop_id: 4676,
      departure_text: "1:23",
      departure_time: 1645730580,
      description: "24St-Uptown / Tyler-Lake / St Louis Pk",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "D",
      schedule_relationship: "NoData",
    },
    {
      actual: false,
      trip_id: "20560470-DEC21-MVS-BUS-Weekday-01",
      stop_id: 46492,
      departure_text: "1:39",
      departure_time: 1645731540,
      description: "24St-Uptown / Lake-France",
      route_id: "17",
      route_short_name: "17",
      direction_id: 1,
      direction_text: "WB",
      terminal: "B",
      schedule_relationship: "NoData",
    },
  ],
};

export default departure_data;
